---
title: "AnalysisPipelineMediod"
author: "Kevin Shin"
date: "5/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
library(tidytext)
library(dplyr)
library(stringr)
library(tokenizers)
library(gutenbergr)
library(rapportools)
library(textstem)
library(text2vec)
library(stopwords)
library(TDA)
library(philentropy)
library(lsa)
library(quanteda)
library(qlcMatrix)
library(irlba)
library(tm)
library(stringi)
library(utf8)
library(cluster)
```

###Load in Data
```{r}
gutenberg_filtered <- gutenberg_metadata %>% filter(is.na(author)==FALSE) %>% filter(is.na(title)==FALSE) %>% filter(has_text == TRUE) %>%  filter(rights == "Public domain in the USA.") %>% filter(language == "en")
topics <- c("Children's Fiction", "Humor", "Science Fiction", "Adventure", "Biographies")
```

###Selecting categories
```{r}
#returns vector of gutenbergIDs associated with that topic
isolateIDs <- function(category){
  subsetBookshelf <- gutenberg_filtered[grep(category, gutenberg_filtered$gutenberg_bookshelf),]
  #On May 11, gutenberg_id 2149 was not available on any mirror for download on gutenbergr
  subsetBookshelf <- subsetBookshelf$gutenberg_id[subsetBookshelf$gutenberg_id != 24450]
  subsetBookshelf <- subsetBookshelf[subsetBookshelf != 19513]
  subsetBookshelf <- subsetBookshelf[subsetBookshelf != 19515]
  subsetBookshelf <- subsetBookshelf[subsetBookshelf != 19526]
  subsetBookshelf <- subsetBookshelf[subsetBookshelf != 4290]
  subsetBookshelf <- subsetBookshelf[1:100]
  subsetBookshelf <- subsetBookshelf[!is.na(subsetBookshelf)]
  return(subsetBookshelf)
}
```

```{r}
set.seed(471)

children <- isolateIDs("Children's Fiction")
humor <- isolateIDs("Humor")
scifi <- isolateIDs("Science Fiction")
adventure <- isolateIDs("Adventure")
biographies <- isolateIDs("Biographies")

bookIndexing <- c(length(children), length(humor), length(scifi), length(adventure), length(biographies))
#print(min(bookIndexing))
#returns 47

children <- sample(children, 45, replace=FALSE, prob=NULL)
humor <- sample(humor, 45, replace=FALSE, prob=NULL)
scifi <- sample(scifi, 45, replace=FALSE, prob=NULL)
adventure <- sample(adventure, 45, replace=FALSE, prob=NULL)
biographies <- sample(biographies, 45, replace=FALSE, prob=NULL)

bookList <- c(children, humor, scifi, adventure, biographies)
bookList <-
```

###Approach 2
```{r}
collection <- bookList

clusteringPD <- function(numLines){
  similarityMatrix <- matrix(ncol = length(collection), nrow = length(collection))
  diag(similarityMatrix) <- 0
  for (bookIndexHoriz in 1:length(collection)){
    for (bookIndexVert in 1:length(collection)){
      if (bookIndexVert > bookIndexHoriz){
        bookDTM <- computeDTM(collection[bookIndexVert],numLines)
        otherBookDTM <- computeDTM(collection[bookIndexHoriz],numLines)
        if (!is.null(bookDTM) && !is.na(otherBookDTM)){  
          bookDistanceMatrix <- makeDistanceMatrix(bookDTM)
          otherBookDistanceMatrix <- makeDistanceMatrix(otherBookDTM)
          Diag <- ripsDiag(X = bookDistanceMatrix,
                           maxdimension = 1,
                           maxscale = 100,
                           dist = "arbitrary", 
                           library = "Dionysus",
                           printProgress = FALSE, 
                           location=TRUE)
          DiagOther <- ripsDiag(X = otherBookDistanceMatrix,
                           maxdimension = 1,
                           maxscale = 100,
                           dist = "arbitrary", 
                           library = "Dionysus",
                           printProgress = FALSE, 
                           location=TRUE)
          wassersteinDist <- wasserstein(Diag[["diagram"]], DiagOther[["diagram"]], p = 2, dimension = 1)
          similarityMatrix[bookIndexHoriz,bookIndexVert] <- wassersteinDist
        }
      }
      else {
        similarityMatrix[bookIndexHoriz,bookIndexVert] <- 0
      }
    }
  }
  mainMatrix <- similarityMatrix + t(similarityMatrix)
  toReturn <- as.data.frame(mainMatrix)
  colnames(toReturn) <- collection
  rownames(toReturn) <- collection
  return(toReturn)
  
}
```

```{r}
similarityTable <- clusteringPD(100)
pamx <- pam(similarityTable, 5, diss = FALSE, cluster.only = FALSE, metric = "manhattan")
```

