---
title: "AnalysisPipelineStatistic"
author: "Kevin Shin"
date: "5/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
library(tidytext)
library(dplyr)
library(stringr)
library(tokenizers)
library(gutenbergr)
library(rapportools)
library(textstem)
library(text2vec)
library(stopwords)
library(TDA)
library(philentropy) 
library(lsa)
library(quanteda)
library(qlcMatrix)
library(irlba)
library(tm)
library(stringi)
library(utf8)
```

###Load in Data
```{r}
gutenberg_filtered <- gutenberg_metadata %>% filter(is.na(author)==FALSE) %>% filter(is.na(title)==FALSE) %>% filter(has_text == TRUE) %>%  filter(rights == "Public domain in the USA.") %>% filter(language == "en")
topics <- c("Children's Fiction", "Humor", "Science Fiction", "Adventure", "Biographies")
```

###Selecting categories
```{r}
#returns vector of gutenbergIDs associated with that topic
isolateIDs <- function(category){
  subsetBookshelf <- gutenberg_filtered[grep(category, gutenberg_filtered$gutenberg_bookshelf),]
  #On May 11, gutenberg_id 2149 was not available on any mirror for download on gutenbergr
  subsetBookshelf <- subsetBookshelf$gutenberg_id[subsetBookshelf$gutenberg_id != 24450]
  subsetBookshelf <- subsetBookshelf[subsetBookshelf != 19513]
  subsetBookshelf <- subsetBookshelf[subsetBookshelf != 19515]
  subsetBookshelf <- subsetBookshelf[subsetBookshelf != 19526]
  subsetBookshelf <- subsetBookshelf[subsetBookshelf != 4290]
  return(subsetBookshelf[1:100])
}
```

```{r}
set.seed(471)

children <- isolateIDs("Children's Fiction")
humor <- isolateIDs("Humor")
scifi <- isolateIDs("Science Fiction")
adventure <- isolateIDs("Adventure")
biographies <- isolateIDs("Biographies")

bookIndexing <- c(length(children), length(humor), length(scifi), length(adventure), length(biographies))
print(min(bookIndexing))
#returns 47

children <- sample(children, 47, replace=FALSE, prob=NULL)
humor <- sample(humor, 47, replace=FALSE, prob=NULL)
scifi <- sample(scifi, 47, replace=FALSE, prob=NULL)
adventure <- sample(adventure, 47, replace=FALSE, prob=NULL)
biographies <- sample(biographies, 47, replace=FALSE, prob=NULL)

bookList <- c(children, humor, scifi, adventure, biographies)

#for consistency across computers
bookList <- c(293,836,7862,8732,7006,5348,3429,530,7831,3785,998,11565,4660,3653,8670,874,11609,11602,9745,5623,2805,5417,5828,5075,6461,10340,1573,7493,770,3674,7037,3811,11151,528,296,7229,5747,5696,11111,5207,8679,399,646,10724,7124,2183,8713,22518,23338,6837,13647,9449,13872,24313,13993,6984,6768,6985,7464,13650,6836,4064,7298,6927,20633,22145,6840,4020,21427,23783,8176,2005,8931,3425,6879,20532,13648,24018,18881,4075,972,7833,8178,22689,4729, 14667, 11138,  2607,  4682, 14684,  7250, 10662,    84,   36,  7246,  7248, 18151,   605,    42, 13944,  7052,  9194, 11696,   551,    68,   159,   552,  8673, 17355,   123,   553,   149, 18137,  6585, 11870,  1329,  6903,  9862,  1607,  7401, 12901,  3479,  2488,   369,    86,  7244,    96,  1250,  6717,   604, 17958,  7242, 18109,   126,  1951,  2759,  5174, 18970,   558,    60, 2166,  5194,   103,  2710,  1690,  5745,  1259, 19307,  1724,  5746,   559, 10422,   848,  1947,    78,  2681, 24920,  2713,  5315,    92,  1257,  1184,   589,   421,  2785, 27525,  1752,  6751,711, 1965,    85,  3526,  1145, 10743,  1711,  2727,  6769,  2609,   106,  2226, 16965, 45456, 19767,   590, 12406, 14555,   813, 16469, 10598,  1702, 21091,  4689, 12014,  1265,  9069, 21677,20733,  4667,   412, 12090, 45532, 14392, 13888,  2563,  6312,  2082,   529, 12985, 12984,  4691, 14992, 20439,  4690, 22345,  6702, 10622, 18757,  4693, 17388, 14004, 10986,  8770,  2447,  3029, 539)
```


###Create DTM
```{r}
computeDTM <- function(IDNum, lineLimit){
  book <- gutenberg_download(IDNum, strip=TRUE)
  book <- transmute(book, gutenberg_id = gutenberg_id, text = iconv(book$text,"UTF-8","UTF-8",sub=''))
  book <- unnest_tokens(book,input="text",output="Paragraph",token="paragraphs")
  book <- book[50:(50+lineLimit),]
  book <- book %>% filter(!is.na(book$Paragraph))
  book <- VCorpus(VectorSource(book$Paragraph))
  book <- tm_map(book, stripWhitespace)
  book <- tm_map(book, content_transformer(tolower))
  book <- tm_map(book, removeWords, stopwords("english"))
  book <- tm_map(book, removePunctuation)
  book <- tm_map(book, stemDocument, language = "english")  
  dtm <- DocumentTermMatrix(book)
  dtm <- weightTfIdf(dtm)

  if ((dim(dtm)[2]) > 1){
    dtmLSA <- lsa(dtm, dims=dimcalc_share())$tk
    return(dtmLSA)
  } else {
    return(NULL)
  }
}

```

###makeDistanceMatrix
```{r}
makeDistanceMatrix <- function(datamatrix){
  distanceMatrix <- datamatrix
  cosineDistMatrix <- cosSparse(distanceMatrix)
  diag(cosineDistMatrix) <- 0
  for(row in 2:nrow(cosineDistMatrix)) {
      cosineDistMatrix[row, row-1] <- 0
      cosineDistMatrix[row-1, row] <- 0 
  }
   for(row in 1:nrow(cosineDistMatrix)) {
     for(col in 1:nrow(cosineDistMatrix)) {
       cosineDistMatrix[row,col] = abs(cosineDistMatrix[row,col])*1000000000000000000
     }
   }
  return(as.matrix(cosineDistMatrix))
}
```

###Main function
```{r}
mainDataFrame <- data.frame(matrix(ncol = 8, nrow = 0))
columns <- c("bookID", "numHoles", "category", "averageBirthLocation", "birthLocationSD", "averageDeathLocation", "deathLocationSD", "avgLengthofLife")
colnames(mainDataFrame) <- columns

main <- function(numLines){
  for (category in topics){
    bookShieldIDs <- isolateIDs(category)
    for (value in bookShieldIDs){
      bookDTM <- computeDTM(value,numLines)
      print(value)
      if (!is.null(bookDTM)){  
        bookDistanceMatrix <- makeDistanceMatrix(bookDTM)
        Diag <- ripsDiag(X = bookDistanceMatrix,
                         maxdimension = 1,
                         maxscale = 100,
                         dist = "arbitrary", 
                         library = "Dionysus",
                         printProgress = FALSE, 
                         location=TRUE)

        numHoles <- summary.diagram(Diag[["diagram"]])$n
        print(numHoles)
        tempDF <- data.frame(value, numHoles, category, mean(Diag$birthLocation), sd(Diag$birthLocation), mean(Diag$deathLocation), sd(Diag$deathLocation), mean(Diag$deathLocation- Diag$birthLocation))
        names(tempDF) <- c("bookID", "numHoles", "category", "averageBirthLocation", "birthLocationSD", "averageDeathLocation", "deathLocationSD", "avgLengthofLife")
        mainDataFrame <- rbind(mainDataFrame,tempDF)
        
      }
      else {
        print("0 here")
        tempDF <- data.frame(value, 0, category, 0, 0, 0, 0, 0)
        names(tempDF) <- c("bookID", "numHoles", "category", "averageBirthLocation", "birthLocationSD", "averageDeathLocation", "deathLocationSD", "avgLengthofLife")
        mainDataFrame <- rbind(mainDataFrame,tempDF)
      }
    }
  }
  return(mainDataFrame)
}

```

```{r}
Statistics <- c("numHoles","averageBirthLocation", "averageDeathLocation","avgLengthofLife")

compareStatistics <- function(dataFrame, statistic){
    df <- data.frame(matrix(0, ncol = 5, nrow = 5))
    colnames(df) <- topics
    rownames(df) <- topics
    for (row in rownames(df)){
      for (col in colnames(df)){
        genreRowTable <- dataFrame %>% filter(category == row)
        genreColTable <- dataFrame %>% filter(category == col)
        significanceLevel <- t.test(genreRowTable$statistic, genreColTable$statistic)$p.value
        df[row,col] <- significanceLevel
      }
    }
    return(df)
}

```





























###Examples and Calls

```{r}
mainDataFrame <- main(100)
View(mainDataFrame)
```



```{r}
DTM_1257 <- computeDTM(1257, 120)
DM_1257 <- makeDistanceMatrix(DTM_1257)

Diag1257 <- ripsDiag(X = DM_1257,
                 maxdimension = 1,
                 maxscale = 50,
                 dist = "arbitrary", 
                 library = "Dionysus",
                 printProgress = FALSE, 
                 location=TRUE)

print(summary.diagram(Diag1257[["diagram"]]))
print("Hit here")
print(mean(Diag1257$birthLocation))
print(sd(Diag1257$birthLocation))
print(mean(Diag1257$deathLocation))
print(sd(Diag1257$deathLocation))
print(mean(Diag1257$birthLocation-Diag1257$deathLocation))
plot(Diag1257[["diagram"]])
plot(Diag1257[["diagram"]], barcode=TRUE, main="Barcode from DTM_1257")

```

```{r}
##Adventure, Three Musketeers
DTM_1257 <- computeDTM(1257, 50)
DM_1257 <- makeDistanceMatrix(DTM_1257)
print(DM_1257)

##Humor, A Damsel in Distress PG Wodehouse
DTM_2233 <- computeDTM(2233, 50)
DM_2233 <- makeDistanceMatrix(DTM_2233)
print(DM_2233)
```



```{r}
DTM_6995 <- gutenberg_download(6995,strip=TRUE)
DTM_6995_STRI <- transmute(DTM_6995, gutenberg_id = gutenberg_id, text = stri_enc_toutf8(DTM_6995$text, is_unknown_8bit = TRUE, validate = TRUE))

DTM_6995_UTF <- transmute(DTM_6995, gutenberg_id = gutenberg_id, text = iconv(DTM_6995$text,"UTF-8","UTF-8",sub=''))

#book <- unnest_tokens(DTM_6995_STRI,input="text",output="Paragraph",token="paragraphs")
book2 <- unnest_tokens(DTM_6995_UTF,input="text",output="Paragraph",token="paragraphs")

```


```{r}
DTM_2233 <- computeDTM(2233, 120)
DM_2233 <- makeDistanceMatrix(DTM_2233)

Diag2233 <- ripsDiag(X = DM_2233,
                 maxdimension = 1,
                 maxscale = 4,
                 dist = "arbitrary", 
                 library = "Dionysus",
                 printProgress = FALSE)

print(summary.diagram(Diag2233[["diagram"]]))
plot(Diag2233[["diagram"]])
print(Diag2233[["diagram"]])
plot(Diag2233[["diagram"]], barcode=TRUE, main="Barcode from DTM_2233")

```


```{r}
DTM_2233 <- computeDTM(30324, 120)
DM_2233 <- makeDistanceMatrix(DTM_2233)

Diag2233 <- ripsDiag(X = DM_2233,
                 maxdimension = 1,
                 maxscale = 1,
                 dist = "arbitrary", 
                 library = "Dionysus",
                 printProgress = FALSE)

print(summary.diagram(Diag2233[["diagram"]]))
plot(Diag2233[["diagram"]])
plot(Diag2233[["diagram"]], barcode=TRUE, main="Barcode from DTM_30324")


```

```{r}
lineLimit <- 50
for (category in topics) {
    bookShieldIDs <- isolateIDs(category)
    for (value in bookShieldIDs) {
      print("NEW BOOK")  
      print(value)
        book <- gutenberg_download(value, strip=TRUE)
        book <- transmute(book, gutenberg_id = gutenberg_id, text = iconv(book$text,"UTF-8","UTF-8",sub=''))
        book <- unnest_tokens(book,input="text",output="Paragraph",token="paragraphs")
        print(nrow(book))
        book <- book[20:(20+lineLimit),]
        print(book)
        book <- book %>% filter(!is.na(book$Paragraph))
        print("I'm filtered")
        print(book)
        print(nrow(book))
    }
}
```


```{r}
for (book in children){
  print(book)
  book <- gutenberg_download(book, strip=TRUE)
  View(book)
  book <- transmute(book, gutenberg_id = gutenberg_id, text = iconv(book$text,"UTF-8","UTF-8",sub=''))
}


```

```{r}
#topics <- c("Children's Fiction", "Humor", "Science Fiction", "Adventure", "Reference", "Horror")

for (bookID in bookList){
  print(bookID)
  book <- gutenberg_download(bookID, strip=TRUE)
  book <- transmute(book, gutenberg_id = gutenberg_id, text = iconv(book$text,"UTF-8","UTF-8",sub=''))
}


```
