---
title: "TopologyDataPipeline"
author: "Kevin Shin"
date: "5/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
library(tidytext)
library(dplyr)
library(stringr)
library(tokenizers)
library(gutenbergr)
library(rapportools)
library(textstem)
library(text2vec)
library(stopwords)
library(TDA)
library(philentropy)
library(lsa)
library(quanteda)
library(qlcMatrix)
library(irlba)
library(tm)
library(stringi)
library(utf8)
```

###Load in Data
```{r}
gutenberg_filtered <- gutenberg_metadata %>% filter(is.na(author)==FALSE) %>% filter(is.na(title)==FALSE) %>% filter(has_text == TRUE) %>%  filter(rights == "Public domain in the USA.") %>% filter(language == "en")
```

###Selecting categories
```{r}
topics <- c("Children's Fiction", "Humor", "Science Fiction", "Adventure", "Reference", "Horror")

#returns vector of gutenbergIDs associated with that topic
isolateIDs <- function(category){
  subsetBookshelf <- gutenberg_filtered[grep(category, gutenberg_filtered$gutenberg_bookshelf),]
  return(subsetBookshelf$gutenberg_id)
}
```

###Main function
```{r}

topics <- c("Horror")
#topics <- c("Children's Fiction", "Humor", "Science Fiction", "Adventure", "Reference", "Horror")

mainDataFrame <- data.frame(matrix(ncol = 8, nrow = 0))
columns <- c("bookID", "numHoles", "category", "averageBirthLocation", "birthLocationSD", "averageDeathLocation", "deathLocationSD", "avgLengthofLife")
colnames(mainDataFrame) <- columns


main <- function(numLines){
  for (category in topics){
    bookShieldIDs <- isolateIDs(category)
    for (value in bookShieldIDs){
      bookDTM <- computeDTM(value,numLines)
      if (!is.null(bookDTM)){  
        bookDistanceMatrix <- makeDistanceMatrix(bookDTM)
        Diag <- ripsDiag(X = bookDistanceMatrix,
                         maxdimension = 1,
                         maxscale = 100,
                         dist = "arbitrary", 
                         library = "Dionysus",
                         printProgress = FALSE, 
                         location=TRUE)

        numHoles <- summary.diagram(Diag[["diagram"]])$n
        tempDF <- data.frame(value, numHoles, category, mean(Diag$birthLocation), sd(Diag$birthLocation), mean(Diag$deathLocation), sd(Diag$deathLocation), mean(Diag$deathLocation- Diag$birthLocation))
        names(tempDF) <- c("bookID", "numHoles", "category", "averageBirthLocation", "birthLocationSD", "averageDeathLocation", "deathLocationSD", "avgLengthofLife")
        mainDataFrame <- rbind(mainDataFrame,tempDF)
        
      }
      else {
        print("0 here")
        tempDF <- data.frame(value, 0, category, 0, 0, 0, 0, 0)
        names(tempDF) <- c("bookID", "numHoles", "category", "averageBirthLocation", "birthLocationSD", "averageDeathLocation", "deathLocationSD", "avgLengthofLife")
        mainDataFrame <- rbind(mainDataFrame,tempDF)
      }
    }
  }
  return(mainDataFrame)
}

main(20)
```

###pipeline
```{r}
pipeline <- function(category, numLines){
  bookShieldIDs <- isolateIDs(category)
  mainDataFrame <- data.frame(bookShieldIDs, numHoles = 0, bookshelf = category)
  
 for (value in bookShieldIDs){
   bookDTM <- computeDTM(value,numLines)
   if (!is.null(bookDTM)){  
   bookDistanceMatrix <- makeDistanceMatrix(bookDTM)
     Diag <- ripsDiag(X = bookDistanceMatrix,
                   maxdimension = 1,
                   maxscale = 100,
                   dist = "arbitrary", 
                   library = "Dionysus",
                   printProgress = FALSE)
     numHoles <- summary.diagram(Diag[["diagram"]])$n
     print(numHoles)
     mainDataFrame$numHoles[mainDataFrame$bookShieldIDs == value] <- numHoles
   }
   else {
     mainDataFrame$numHoles[mainDataFrame$bookShieldIDs == value] <- 0
     print("0 here")
   }
 }
  return(mainDataFrame)
}


```


###Create DTM
```{r}
computeDTM <- function(IDNum, lineLimit){
  book <- gutenberg_download(IDNum, strip=TRUE)
  book <- transmute(book, gutenberg_id = gutenberg_id, text = iconv(book$text,"UTF-8","UTF-8",sub=''))
  book <- unnest_tokens(book,input="text",output="Paragraph",token="paragraphs")
  book <- book[50:(50+lineLimit),]
  book <- book %>% filter(!is.na(book$Paragraph))
  book <- VCorpus(VectorSource(book$Paragraph))
  book <- tm_map(book, stripWhitespace)
  book <- tm_map(book, content_transformer(tolower))
  book <- tm_map(book, removeWords, stopwords("english"))
  book <- tm_map(book, removePunctuation)
  book <- tm_map(book, stemDocument, language = "english")  
  dtm <- DocumentTermMatrix(book)
  dtm <- weightTfIdf(dtm)

  if ((dim(dtm)[2]) != 0){
    dtmLSA <- lsa(dtm, dims=dimcalc_share())$tk
    return(dtmLSA)
  } else {
    return(NULL)
  }
}

```

###makeDistanceMatrix
```{r}
makeDistanceMatrix <- function(datamatrix){
  distanceMatrix <- datamatrix
  cosineDistMatrix <- cosSparse(distanceMatrix)
  diag(cosineDistMatrix) <- 0
  for(row in 2:nrow(cosineDistMatrix)) {
      cosineDistMatrix[row, row-1] <- 0
      cosineDistMatrix[row-1, row] <- 0 
  }
   for(row in 1:nrow(cosineDistMatrix)) {
     for(col in 1:nrow(cosineDistMatrix)) {
       cosineDistMatrix[row,col] = abs(cosineDistMatrix[row,col])*1000000000000000000
     }
   }
  return(as.matrix(cosineDistMatrix))
}
```

###Examples and Calls

```{r}
main(20)
```



```{r}
DTM_1257 <- computeDTM(1257, 120)
DM_1257 <- makeDistanceMatrix(DTM_1257)

Diag1257 <- ripsDiag(X = DM_1257,
                 maxdimension = 1,
                 maxscale = 50,
                 dist = "arbitrary", 
                 library = "Dionysus",
                 printProgress = FALSE, 
                 location=TRUE)

print(summary.diagram(Diag1257[["diagram"]]))
print("Hit here")
print(mean(Diag1257$birthLocation))
print(sd(Diag1257$birthLocation))
print(mean(Diag1257$deathLocation))
print(sd(Diag1257$deathLocation))
print(mean(Diag1257$birthLocation-Diag1257$deathLocation))
plot(Diag1257[["diagram"]])
plot(Diag1257[["diagram"]], barcode=TRUE, main="Barcode from DTM_1257")

```

```{r}
##Adventure, Three Musketeers
DTM_1257 <- computeDTM(1257, 50)
DM_1257 <- makeDistanceMatrix(DTM_1257)
print(DM_1257)

##Humor, A Damsel in Distress PG Wodehouse
DTM_2233 <- computeDTM(2233, 50)
DM_2233 <- makeDistanceMatrix(DTM_2233)
print(DM_2233)
```



```{r}
DTM_6995 <- gutenberg_download(6995,strip=TRUE)
DTM_6995_STRI <- transmute(DTM_6995, gutenberg_id = gutenberg_id, text = stri_enc_toutf8(DTM_6995$text, is_unknown_8bit = TRUE, validate = TRUE))

DTM_6995_UTF <- transmute(DTM_6995, gutenberg_id = gutenberg_id, text = iconv(DTM_6995$text,"UTF-8","UTF-8",sub=''))

#book <- unnest_tokens(DTM_6995_STRI,input="text",output="Paragraph",token="paragraphs")
book2 <- unnest_tokens(DTM_6995_UTF,input="text",output="Paragraph",token="paragraphs")

```


```{r}
DTM_2233 <- computeDTM(2233, 120)
DM_2233 <- makeDistanceMatrix(DTM_2233)

Diag2233 <- ripsDiag(X = DM_2233,
                 maxdimension = 1,
                 maxscale = 4,
                 dist = "arbitrary", 
                 library = "Dionysus",
                 printProgress = FALSE)

print(summary.diagram(Diag2233[["diagram"]]))
plot(Diag2233[["diagram"]])
print(Diag2233[["diagram"]])
plot(Diag2233[["diagram"]], barcode=TRUE, main="Barcode from DTM_2233")

```


```{r}
DTM_2233 <- computeDTM(30324, 120)
DM_2233 <- makeDistanceMatrix(DTM_2233)

Diag2233 <- ripsDiag(X = DM_2233,
                 maxdimension = 1,
                 maxscale = 1,
                 dist = "arbitrary", 
                 library = "Dionysus",
                 printProgress = FALSE)

print(summary.diagram(Diag2233[["diagram"]]))
plot(Diag2233[["diagram"]])
plot(Diag2233[["diagram"]], barcode=TRUE, main="Barcode from DTM_30324")


```

```{r}
lineLimit <- 50

for (category in topics) {
    bookShieldIDs <- isolateIDs(category)
    for (value in bookShieldIDs) {
      print("NEW BOOK")  
      print(value)
        book <- gutenberg_download(value, strip=TRUE)
        book <- transmute(book, gutenberg_id = gutenberg_id, text = iconv(book$text,"UTF-8","UTF-8",sub=''))
        book <- unnest_tokens(book,input="text",output="Paragraph",token="paragraphs")
        print(nrow(book))
        book <- book[20:(20+lineLimit),]
        print(book)
        book <- book %>% filter(!is.na(book$Paragraph))
        print("I'm filtered")
        print(book)
        print(nrow(book))
    }
}
```